config/routes.rb
Rails.application.routes.draw do
  root 'home#top'

  get    '/login',  to:'sessions#new'
  post   '/login',  to:'sessions#create'
  delete '/logout', to:'sessions#destroy'

  get    '/users/serch',   to:'users#serch'
  get    '/posts/serch',   to:'posts#serch'

  resources :users do
    member do
      get    :edit_image,   :edit_post, :following, :followed, :setting
      delete :admin_destroy #管理者権限による削除
      patch  :update_image, :update_post, :update_setting
    end
  end

  resources :posts
  resources :likes,               only:[:create, :destroy]
  resources :relationships,       only:[:create, :destroy]
  resources :account_activations, only:[:edit]

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :followed,  class_name: 'User'

  validates :following_id, presence: true
  validates :followed_id,  presence: true
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user

  def create
    @user = User.find(params[:followed_id])
    unless current_user?(@user)
      current_user.following_relationships.create(followed_id: @user.id)
    end
    render 'follow.js.erb'
  end

  def destroy
    @user = User.find_by(id: params[:id])
    if @user.present?
      @relationship = current_user.following_relationships.find_by(followed_id: @user.id)
      @relationship.destroy
      render 'follow.js.erb'
    else
      redirect_to root_path
    end
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_form.html.erb
<% if current_user.present? && current_user.followings.find_by(id: @user.id) %>
  <%= link_to "フォロー中", relationship_path(@user),
                              {class: "follow_btn followed",
                               method: :delete,
                               remote: true} %>
<% else %>
  <%= link_to "フォローする", relationships_path(followed_id: @user.id),
                            {class: "follow_btn following",
                             method: :post,
                             remote: true} %>
<% end %>

app/views/relationships/_follows_form.html.erb
follow：<%= link_to @user.followings.count, following_user_path(@user) %>
follower：<%= link_to @user.followers.count, followed_user_path(@user) %>

app/views/relationships/follow.js.erb
$('#follow_btn').html(
    "<%= escape_javascript(render partial: 'relationships/follow_form',
                                  local: {user: @user}) %>"
)

$('#follows').html(
    "<%= escape_javascript(render partial: 'relationships/follows_form',
                                  local: {user: @user}) %>"
)