config/routes.rb
Rails.application.routes.draw do
  root 'home#top'

  get    '/login',  to:'sessions#new'
  post   '/login',  to:'sessions#create'
  delete '/logout', to:'sessions#destroy'

  get    '/users/serch',   to:'users#serch'
  get    '/posts/serch',   to:'posts#serch'

  resources :users do
    member do
      get    :edit_image,   :edit_post, :following, :followed, :setting
      delete :admin_destroy #管理者権限による削除
      patch  :update_image, :update_post, :update_setting
    end
  end

  resources :posts
  resources :likes,               only:[:create, :destroy]
  resources :relationships,       only:[:create, :destroy]
  resources :account_activations, only:[:edit]

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post

  has_many :following_relationships, class_name: 'Relationship',
                                     foreign_key: :following_id,
                                     dependent: :destroy
  has_many :followed_relationships,  class_name: 'Relationship',
                                     foreign_key: :followed_id,
                                     dependent: :destroy
  has_many :followings, through: :following_relationships, source: :followed
  has_many :followers,  through: :followed_relationships,  source: :following

  validates :name,  presence: true, length:{maximum:30}
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length:{minimum:8}, allow_nil: true
  validates :introduction, length:{maximum:180}

  mount_uploader :image_user, UserImageUploader

  before_save   :downcase_email
  before_create :create_activation_digest

  #パスワードのハッシュ化
  def User.digest(password)
    BCrypt::Password.create(password)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  private

    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,  only: [:edit, :update, :destroy, :edit_image, :update_image,
                                         :admin_destroy, :setting, :update_setting]
  before_action :correct_user,    only: [:edit, :update, :destroy, :edit_image, :update_image,
                                         :setting, :update_setting]
  before_action :user_admin?,     only:  :admin_destroy
  before_action :not_user_admin?, only:  :destroy

  def index
    @users = User.all.order(created_at: "DESC").page(params[:page]).per(10)
  end

  def show
    @user = User.find_by(id: params[:id])
    if @user.present?
      @posts = @user.posts.page(params[:page]).per(9)
    else
      redirect_to users_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "メールを送信しました。メールをご確認ください。"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(edit_params)
      flash[:success] = "プロフィールを更新しました！"
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:info] = "退会しました"
    logout
    redirect_to root_path
  end

  def admin_destroy
    @user = User.find_by(id: params[:id])
    if @user.present? && !current_user?(@user)
      @user.destroy
      flash[:info] = "削除しました"
    end
    redirect_to users_path
  end

  def edit_image
  end

  def update_image
    if @user.update(image_params)
      flash[:success] = "画像を更新しました"
      redirect_to user_path(@user)
    else
      render 'edit_image'
    end
  end

  def following
    @title = 'フォロー'
    users = User.find_by(id: params[:id])
    if users.present?
      @users = users.followings.page(params[:page]).per(10)
      render 'index'
    else
      redirect_to root_path
    end
  end

  def followed
    @title = 'フォロワー'
    users  = User.find_by(id: params[:id])
    if users.present?
      @users = users.followers.page(params[:page]).per(10)
      render 'index'
    else
      redirect_to root_path
    end
  end

  def serch
    users = User.where('name LIKE ?', "%#{params[:name]}%")
    @users = users.order(created_at: "DESC").page(params[:page]).per(10)
    @serch = params[:name]
    render 'index'
  end

  def setting
  end

  def update_setting
    if @user.update(setting_params)
      flash[:success] = "設定を変更しました！"
      redirect_to root_path
    else
      render 'setting'
    end
  end


  private

    def user_params
      params.require(:user).permit(:name,
                                   :email,
                                   :password,
                                   :password_confirmation)
    end

    def edit_params
      params.require(:user).permit(:name, :introduction)
    end

    def image_params
      params.require(:image).permit(:image_user)
    end

    def setting_params
      params.require(:setting).permit(:email,
                                      :password,
                                      :password_confirmation)
    end

    def correct_user
      @user = User.find_by(id: params[:id])
      redirect_to root_path if @user.nil? || !current_user?(@user)
    end

    def user_admin?
      redirect_to root_path unless current_user.admin?
    end

    def not_user_admin?
      redirect_to root_path if current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div class="UserIndex-item">
  <div class="UserIndex-left">
    <% if user.image_user.present? %>
      <%= image_tag(user.image_user_url(:thumb), class: "UserIndex-image") %>
    <% else %>
      <img src="/assets/default_user_mini.png">
    <% end %>
    <% if current_user && current_user.admin? && !current_user?(user) %>
      <%= link_to "削除", admin_destroy_user_path(user), {class: "UserIndex-delete",
                                                         method: :delete,
                                                         data:{confirm: "#{user.name}さんを削除していいですか？"}} %>
    <% end %>
  </div>

  <div class="UserIndex-right">
    <div>
      <%= link_to user.name, user_path(user), {class: "Link UserIndex-name"} %>
    </div>

    <div class="UserIndex-postCount">
      投稿数：<%= user.posts.count %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="UserEdit-wrapper">
  <%= form_with(model: @user, local: true) do |form| %>
    <%= render 'layouts/error_message', object: form.object %>

    <div class="UserEdit-content">
      <div class="UserEdit-left">
        <div class="UserEdit-image-wrapper">
          <li><%= link_to image_tag(@user.image_user_url, class: "UserEdit-image"),
                          edit_image_user_path(@user) %></li>
          <i class="fas fa-2x fa-camera UserEdit-fontImage"></i>
        </div>
      </div>

      <div class="UserEdit-form">
        <%= form.label :名前, {class: "form-label"} %>
        <%= form.text_field :name, {id: "UserEdit-name",
                                    class: "form-field UserEdit-name",
                                    maxlength: 30} %>
        <p id="name-counter"><%= @user.name.length %>文字 / 30文字</p>

        <%= form.label :自己紹介, {class: "form-label"} %>
        <%= form.text_area :introduction, {id: "UserEdit-introduction",
                                           class: "form-field UserEdit-introduction",
                                           maxlength: 180} %>

        <p id="introduction-counter">
          <% if @user.introduction.present? %>
            <%= @user.introduction.length %>文字 / 180文字
          <% else %>
            0文字 / 180文字
          <% end %>
        </p>

        <%= form.submit "更新する", {class: "btn UserEdit-btn"} %>

      </div>
    </div>



  <% end %>
</div>

app/views/users/edit_image.html.erb
<div class="imageUpload-wrapper">
  <h1>画像のアップロード</h1>

  <div class="imageUpload-form">
    <%= form_with(model: @user, url: update_image_user_path(@user), scope: :image,
                                                                    local: true,
                                                                    method: :patch) do |form| %>
      <%= render 'layouts/error_message', object: form.object %>

      <%= form.file_field :image_user, {class: "imageUpload-field"} %>
      <%= form.hidden_field :image_user_cashe %>

      <%= form.submit "アップロード", {class: "btn form-btn"} %>

    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% if @serch.present? %>
  <div class="serch">
    ”<%= @serch %>”の検索結果
  </div>
<% end %>

<% if @title.present? %>
  <h1 class="title">
    <%= @title %>
  </h1>
<% end %>

<div class="UserIndex-wrapper">

  <%= paginate @users %>

  <div class="UserIndex-items">
    <%= render @users %>
  </div>

  <%= paginate @users %>

</div>

app/views/users/new.html.erb
<div class="UserCreate-wrapper">
  <h1>新規登録</h1>

  <%= form_with(model: @user, local: true) do |form| %>
    <%= render 'layouts/error_message', object: form.object %>

    <div class="UserCreate-form">
      <%= form.label :名前, {class: "form-label"} %>
      <%= form.text_field :name, {class: "form-field User-field"} %>

      <%= form.label :メール, {class: "form-label"} %>
      <%= form.email_field :email, {class: "form-field User-field"} %>

      <%= form.label :パスワード（8文字以上）, {class: "form-label"} %>
      <%= form.password_field :password, {class: "form-field User-field"} %>

      <%= form.label :パスワード確認, {class: "form-label"} %>
      <%= form.password_field :password_confirmation, {class: "form-field User-field"} %>

      <%= form.submit "新規登録", {class: "btn form-btn User-btn"} %>

    <% end %>
  </div>
</div>

app/views/users/serch.js.erb
$('#users').html(
    "<%= escape_javascript(render partial: '',
                                  local: {user: @user}) %>"
)

app/views/users/setting.html.erb
<div class="UserSetting-wrapper">
  <h1>個人情報の変更</h1>

  <%= form_with(model: @user, url: update_setting_user_path(@user), scope: :setting,
                                                 local: true) do |form| %>
    <%= render 'layouts/error_message', object: form.object %>

    <div class="UserSetting-form">
      <%= form.label :メール, {class: "form-label"} %>
      <%= form.email_field :email, {class: "form-field User-field"} %>

      <%= form.label :パスワード, {class: "form-label"} %>
      <%= form.password_field :password, {class: "form-field User-field"} %>

      <%= form.label :パスワード確認, {class: "form-label"} %>
      <%= form.password_field :password_confirmation, {class: "form-field User-field"} %>

      <%= form.submit "更新する", {class: "btn form-btn User-btn"} %>

    <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="UserProfile-wrapper">
  <% if current_user?(@user) %>
    <div class="UserProfile-editLink">
      <%= link_to "プロフィールを編集", edit_user_path, {class: "Link editLink"} %>
    </div>
  <% else %>
    <div id="follow_btn">
      <%= render 'relationships/follow_form', user: @user %>
    </div>
  <% end %>

  <div class="UserProfile-left">
    <div class="UserProfile-image-wrapper">
      <%= image_tag(@user.image_user_url, class: "UserProfile-image") %>
    </div>
    <div id="follows">
      <%= render 'relationships/follows_form', user: @user %>
    </div>
  </div>

  <div class="UserProfile-right">
    <div class="UserProfile-name">
        <%= @user.name %>
    </div>
    <div class="UserProfile-introduction">
      <%= @user.introduction %>
    </div>
  </div>
</div>

<div class="UserProfile-PostItems-wrapper">
  <ul class="UserProfile-tab">
    <li class="tab-posts active">
      <%= link_to posts_path(user_id: @user.id, flg: "1"), remote: true do %>
        <i class="fas fa-tag">投稿記事</i>
      <% end %>
    </li>
    <li class="tab-likes">
      <%= link_to posts_path(user_id: @user.id, flg: "2"), remote: true do %>
        <i class="fas fa-tag">お気に入り</i>
      <% end %>
    </li>
  </ul>

  <div id="UserProfile-PostItems">
    <%= paginate @posts %>
    <div class="UserProfile-PostItems">
      <%= render @posts %>
    </div>
    <%= paginate @posts %>
  </div>
</div>