config/routes.rb
Rails.application.routes.draw do
  root 'home#top'

  get    '/login',  to:'sessions#new'
  post   '/login',  to:'sessions#create'
  delete '/logout', to:'sessions#destroy'

  get    '/users/serch',   to:'users#serch'
  get    '/posts/serch',   to:'posts#serch'

  resources :users do
    member do
      get    :edit_image,   :edit_post, :following, :followed, :setting
      delete :admin_destroy #管理者権限による削除
      patch  :update_image, :update_post, :update_setting
    end
  end

  resources :posts
  resources :likes,               only:[:create, :destroy]
  resources :relationships,       only:[:create, :destroy]
  resources :account_activations, only:[:edit]

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many   :spots, dependent: :destroy
  has_many   :likes, dependent: :destroy
  has_many   :users, through: :likes, foreign_key: :post_id

  mount_uploader :image_post, PostImageUploader

  validates :title, presence: true, length:{maximum: 30}
  validates :place, presence: true, length:{maximum: 10}
  validates :overview, presence: true, length:{maximum: 100}

  accepts_nested_attributes_for :spots, allow_destroy: true



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :destroy]

  def index
    user = User.find_by(id: params[:user_id])
    @flg = params[:flg]
    if user.present? && @flg == "1"
      #投稿記事タブを押下した場合
      @posts = user.posts.order(created_at: "DESC").page(params[:page]).per(9)
    elsif user.present? && params[:flg] == "2"
      #お気に入り記事タブを押下した場合
      @posts = user.like_posts.order(created_at: "DESC").page(params[:page]).per(9)
    else
      #タイムライン
      @posts = Post.all.order(created_at: "DESC").page(params[:page]).per(18)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @post = Post.find_by(id:params[:id])
    if @post.present?
      @spots = @post.spots
    else
      redirect_to root_path
    end
  end

  def new
    @post = Post.new
    @post.spots.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:info] = "投稿しました"
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:info] = "更新しました"
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:info] = "記事が削除されました"
    redirect_to posts_path
  end

  def serch
    posts = Post.where('place LIKE ?', "%#{params[:place]}%")
    @posts = posts.order(created_at: "DESC").page(params[:page]).per(18)
    @serch = params[:place]
    render 'index'
  end


  private

    def post_params
      params.require(:post).permit(:title,
                                   :place,
                                   :image_post,
                                   :overview,
                                   spots_attributes:[:id,
                                                     :place,
                                                     :image_spot,
                                                     :explaine,
                                                     :_destroy]
      )
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_path if @post.nil?
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_index.html.erb
<%= paginate @posts %>

<div class="PostIndex-items">
  <%= render @posts %>
</div>

<%= paginate @posts %>

app/views/posts/_post.html.erb
<div class="PostIndex-item">
  <div class="PostIndex-image-wrapper">
    <% if post.image_post.present? %>
      <%= image_tag(post.image_post_url(:thumb), class: "PostIndex-image") %>
    <% else %>
      <div class="PostIndex-image">No Image</div>
    <% end %>
  </div>

  <div class="PostIndex-title-wrapper">
    <%= link_to post.title, post_path(post), {class: "Link"} %>
  </div>
  <div class="PostIndex-info">
    <i class="fas fa-pencil-alt"></i>
    <%= l post.created_at %>
    <i class="fas fa-map-marker-alt"></i>
    <%= post.place %>

    <% if logged_in? && post.users.find_by(id: current_user.id).present? %>
      <i class="fas fa-star yellow"></i>
    <% else %>
      <i class="far fa-star"></i>
    <% end %>
    <%= post.likes.count %>
  </div>
</div>

app/views/posts/_spot_fields.html.erb
<div class="nested-fields">

  <%= link_to_remove_association f, {class: "remove-link"} do %>
    <i class="fas fa-2x fa-times"></i>
  <% end %>

  <%= f.label :スポット名, {class: "form-label"} %>
  <%= f.text_field :place, {class: "form-field SpotPlace-field",
                            maxlength: 20} %>
  <p class="counter SpotPlace-counter">0文字 / 20文字</p>

  <%= f.label :スポット画像, {class: "form-label SpotImage-label"} %>
  <%= f.file_field :image_spot, {class: "form-field SpotImage-field"} %>

  <%= f.label :スポットの見所, {class: "form-label"} %>
  <%= f.text_area :explaine, {class: "form-field SpotExplaine-field",
                              maxlength: 300} %>
  <p class="counter SpotExplaine-counter">0文字 / 300文字</p>

</div>

app/views/posts/edit.html.erb
<div class="PostEdit-wrapper">
  <h1>投稿の編集</h1>

    <%= form_with(model: @post, local: true) do |form| %>
      <%= render 'layouts/error_message', object: form.object %>

      <div class="PostEdit-form">
        <%= form.label :タイトル, {class: "form-label"} %>
        <%= form.text_field :title, {class: "form-field PostTitle-field",
                                     id: "PostTitle",
                                     maxlength: 30} %>
      <p class="counter" id="PostTitle-counter"><%= @post.title.length %>文字 / 30文字</p>

      <div class="PostImage-form-wrapper">
        <%= form.label :記事画像, {class: "form-label PostImage-label"} %>
        <%= form.file_field :image_post, {class: "form-field PostImage-field"} %>
      </div>

      <div class="PostPlace-form-wrapper">
        <%= form.label :地名, {class: "form-label"} %>
        <%= form.text_field :place, {class: "form-field PostPlace-field",
                                     id: "PostPlace",
                                     maxlength: 10} %>
        <p class="counter" id="PostPlace-counter"><%= @post.place.length %>文字 / 10文字</p>
      </div>

      <div class="PostOverview-form-wrapper">
        <%= form.label :概要, {class: "form-label PostOverview-label"} %>
        <%= form.text_area :overview, {class: "form-field PostOverview-field",
                                       id: "PostOverview",
                                       maxlength: 100} %>
        <p class="counter" id="PostOverview-counter"><%= @post.overview.length %>文字 / 100文字</p>
      </div>


      <%= form.fields_for :spots do |spot| %>
        <%= render 'spots/spot_edit', f: spot %>
      <% end %>

      <%= form.submit "更新する", {class: "btn PostEdit-btn"} %>

    <% end %>

  </div>
</div>

app/views/posts/index.html.erb
<% if @serch.present? %>
  <div class="serch">
    ”<%= @serch %>”の検索結果
  </div>
<% end %>

<div class="PostIndex-wrapper">

  <%= render 'posts/index' %>

</div>

app/views/posts/index.js.erb
$('#UserProfile-PostItems').html(
    "<%= escape_javascript(render partial: 'posts/index',
                                  local: {post: @posts}) %>"
)

//タブの切り替え
$('.tab-posts, .tab-likes').removeClass('active');
"<% if @flg == "1" %>"
  $('.tab-posts').addClass('active');
"<% elsif @flg == "2" %>"
  $('.tab-likes').addClass('active');
" <% end %>"

app/views/posts/new.html.erb
<div class="PostCreate-wrapper">
  <h1>お気に入りのコースを投稿しよう</h1>

  <%= form_with(model: @post, local: true) do |form| %>
    <%= render 'layouts/error_message', object: form.object %>

    <div class="PostCreate-form">
      <%= form.label :タイトル, {class: "form-label"} %>
      <%= form.text_field :title, {class: "form-field PostTitle-field",
                                   id: "PostTitle",
                                   maxlength: 30} %>
      <p class="counter" id="PostTitle-counter">0文字 / 30文字</p>

      <div class="PostImage-form-wrapper">
        <%= form.label :記事画像, {class: "form-label PostImage-label"} %>
        <%= form.file_field :image_post, {class: "form-field PostImage-field"} %>
      </div>

      <div class="PostPlace-form-wrapper">
        <%= form.label :地名, {class: "form-label"} %>
        <%= form.text_field :place, {class: "form-field PostPlace-field",
                                     id: "PostPlace",
                                     maxlength: 10} %>
        <p class="counter" id="PostPlace-counter">0文字 / 10文字</p>
      </div>

      <div class="PostOverview-form-wrapper">
        <%= form.label :概要, {class: "form-label PostOverview-label"} %>
        <%= form.text_area :overview, {class: "form-field PostOverview-field",
                                       id: "PostOverview",
                                       maxlength: 100} %>
        <p class="counter" id="PostOverview-counter">0文字 / 100文字</p>
      </div>


      <div id="SpotCreate-form-wrapper">
        <%= form.fields_for :spots do |spot| %>
          <%= render 'spot_fields', f: spot %>
        <% end %>
      </div>

      <%= link_to_add_association form, :spots, id: "add-link",
        data:{
          association_insertion_node: '#SpotCreate-form-wrapper',
          association_insertion_method: 'append'
        } do %>
        <i class="fas fa-plus">スポット追加</i>
      <% end %>

      <%= form.submit "投稿", {class: "btn PostCreate-btn"} %>

    </div>

  <% end %>

</div>

app/views/posts/show.html.erb
<div class="PostShow-wrapper">


  <div class="PostShow-image-wrapper">
    <% if @post.image_post.present? %>
      <%= image_tag(@post.image_post_url, class: "PostShow-image") %>
    <% else %>
      <div class="PostShow-image">No Image</div>
    <% end %>


    <div class="PostShow-currentOnly">
      <% if current_user?(@post.user) %>
        <div class="PostShow-edit-wrapper">
          <%= link_to edit_post_path(@post) do %>
            <i class="far fa-2x fa-edit currentOnly"></i>
          <% end %>
        </div>
        <div class="PostShow-delete-wrpper">
          <%= link_to post_path(@post), {method: :delete, data:{confirm: "この記事を削除しますか？"}} do %>
            <i class="far fa-2x fa-trash-alt currentOnly"></i>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>

  <div class="PostShow-info">
    <div class="PostShow-date">
      <i class="fas fa-pencil-alt"></i>
      ：<%= l @post.created_at %>
    </div>
    <div class="PostShow-name">
      <i class="far fa-user"></i>
      ：<u><%= link_to @post.user.name, user_path(@post.user), {class: "Link"} %></u>
    </div>
  </div>

  <div class="PostShow-title-wrapper">
    <%= @post.title %>
    <div class="PostShow-place-wrapper">
      <i class="fas fa-map-marker-alt PostShow-fontPlace"></i>
      <%= @post.place %>
    </div>
  </div>
</div>

<div class="PostShow-overview-wrapper">
  <%= @post.overview %>
</div>

<div class="Spot-items">
  <%= render @spots %>
</div>

<div id="like_btn">
  <%= render 'likes/like_form', post: @post, like: @like %>
</div>