config/routes.rb
Rails.application.routes.draw do
  root 'home#top'

  get    '/login',  to:'sessions#new'
  post   '/login',  to:'sessions#create'
  delete '/logout', to:'sessions#destroy'

  get    '/users/serch',   to:'users#serch'
  get    '/posts/serch',   to:'posts#serch'

  resources :users do
    member do
      get    :edit_image,   :edit_post, :following, :followed, :setting
      delete :admin_destroy #管理者権限による削除
      patch  :update_image, :update_post, :update_setting
    end
  end

  resources :posts
  resources :likes,               only:[:create, :destroy]
  resources :relationships,       only:[:create, :destroy]
  resources :account_activations, only:[:edit]

end

app/views/layouts/_error_message.html.erb
<% if object.errors.any? %>
  <div class="message error-wrapper">
    <% object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div class="header-container">

    <div class="header-left">
      <%= link_to "favorite", root_path, {class: "Link TitleLink"} %>
    </div>

    <ul class="header-center">
      <li><%= link_to "タイムライン", posts_path, {class: "Link centerLink"} %></li>
      <li>
        <%= form_with(url: users_serch_path, local: true, method: :get) do |form| %>
          <%= form.text_field :name, {class: "UserSerch-Field"} %>
          <%= form.submit "ユーザー検索", {class: "btn UserSerch-btn"} %>
        <% end %>
      </li>
      <li>
        <%= form_with(url: posts_serch_path, local: true, method: :get) do |form| %>
          <%= form.text_field :place, {class: "PostSerch-Field"} %>
          <%= form.submit "スポット検索", {class: "btn PostSerch-btn"} %>
        <% end %>
      </li>
    </ul>

    <ul class="header-right">
      <% if logged_in? %>
        <!-- admin権限あるアカウントは原則削除しない -->
        <% unless current_user.admin? %>
          <li><%= link_to "退会", user_path(current_user), method: :delete,
                                                          class: "Link rightLink",
                                                          data:{confirm: "本当に退会しますか？"} %></li>
        <% end %>
        <li><%= link_to "設定", setting_user_path(current_user), {class: "Link rightLink"} %></li>
        <li><%= link_to "ログアウト", logout_path, {class: "Link rightLink", method: :delete} %></li>
        <li><%= link_to "マイページ", user_path(current_user), {class: "Link rightLink"} %></li>
        <li><%= link_to "投稿", new_post_path, {class: "Link rightLink"} %></li>
      <% else %>
        <li><%= link_to "新規登録", new_user_path, {class: "Link rightLink"} %></li>
        <li><%= link_to "ログイン", login_path, {class: "Link rightLink"} %></li>
      <% end %>
    </ul>

  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FavoriteApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="body-container">
      <% flash.each do |message_type, message| %>
        <div class="message flash flash-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      
    </div>
  </body>
</html>